#!/usr/bin/env python
# The game generate a random number between 0 and 20 and ask the user to guess the number
# if the user guessed wrong, he will be given a hint to help him guess the correct number


import random


# function that get the right number and the guessed number and check if they are the same answer.
def check_guess(right_number, guess_number):
    if right_number > guess_number:
        print("The number you guessed is below the number")
    elif right_number < guess_number:
        print("The number you guessed is above the number")
    else:
        print("congrats! the number " + str(guess_number) + " is the right number!")
        return False


again = True 
while again:  # check if the again is True to play the game again
    valid_answer = False # check if the answer is valid. after it is valid, it get reset for the next loop
    right_num = random.randrange(0, 21)
    guess_num = None
    print("Please guess a number between 0 and 20 ")
    while right_num != guess_num:
        try:
            guess_num = int(input("please insert your guess >>>>> "))
            if 0 < guess_num < 20:
                check_guess(right_num, guess_num)
            else:
                print("Please choose a number between 0 and 20")
        except:
            print("Please choose a valid number")
    while not valid_answer: # checking if the answer to play again is valid or not
        play_again = input("do you want to play again? Y/N\n")
        if play_again == "Y" or play_again == "y" or play_again == "n" or play_again == "N":
            if play_again == "n" or play_again == "N":
                print("thank you for playing")
                valid_answer = True
                again = False
            else:
                print("lets do another round!")
                valid_answer = True
        else:
            print("please choose a valid answer")
