#!/usr/bin/env python

import scapy.all as scapy
import argparse


def get_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("-t", "--target", dest="ip", help="Network Scanner for the target IP")
    options = parser.parse_args()
    if not options.ip:
        parser.error("[-] please specify an IP, use --help for more info.")
    return options


def scan(ip):
#   scapy.ls(scapy.ARP())---- this gives a list to check what options i can use in the ARP
    arp_request = scapy.ARP(pdst=ip)
#   scapy.ls(scapy.Ether())---- this gives a list to check what options i can use in the Ether
    broadcast = scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_request_broadcast = broadcast/arp_request
    answered_list = scapy.srp(arp_request_broadcast, timeout=1, verbose=False)[0]

    clients_list = []
    for element in answered_list:
        client_dict = {"ip": element[1].psrc, "mac": element[1].hwsrc}
        clients_list.append(client_dict)
    return clients_list


def print_result(results_list):
    print("IP\t\t\tMAC Address")
    print("-"*50)
    for client in results_list:
        print(client["ip"] + "\t\t" + client["mac"])


options = get_arguments()
scan_result = scan(options.ip+"/24")
print_result(scan_result)
